# Generated by Django 6.0 on 2026-01-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporateinquiry',
            options={'ordering': ['-created_at']},
        ),
    ]
