# Generated by Django 6.0 on 2026-01-10 17:48

import uuid
from django.db import migrations, models


def generate_email_tokens(apps, schema_editor):
    CustomOrder = apps.get_model("products", "CustomOrder")
    for order in CustomOrder.objects.all():
        order.email_verification_token = uuid.uuid4()
        order.save(update_fields=["email_verification_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_customorder_status_customorderemaillog"),
    ]

    operations = [
        # 1️⃣ Add token field (nullable, no unique yet)
        migrations.AddField(
            model_name="customorder",
            name="email_verification_token",
            field=models.UUIDField(null=True, editable=False),
        ),

        # 2️⃣ Populate unique tokens for existing rows
        migrations.RunPython(generate_email_tokens),

        # 3️⃣ Enforce uniqueness AFTER data exists
        migrations.AlterField(
            model_name="customorder",
            name="email_verification_token",
            field=models.UUIDField(unique=True, editable=False),
        ),

        # 4️⃣ Add email_verified field (this one is safe)
        migrations.AddField(
            model_name="customorder",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
