# Generated by Django 6.0 on 2026-01-10 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_customorder_email_verification_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customorder",
            name="email_verification_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
