# Generated by Django 6.0 on 2026-01-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0008_remove_booking_otp_remove_booking_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experienceslot',
            old_name='booked_participants',
            new_name='booked_slots',
        ),
        migrations.RenameField(
            model_name='experienceslot',
            old_name='max_participants',
            new_name='total_slots',
        ),
        migrations.RemoveField(
            model_name='experienceslot',
            name='min_participants',
        ),
        migrations.AddField(
            model_name='experience',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='min_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
