# Generated by Django 6.0 on 2026-01-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0009_rename_booked_participants_experienceslot_booked_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
